version: '3.8'

services:
  bot:
    build: .
    container_name: file_convert_pro
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./tmp:/app/tmp
      - ./bot.db:/app/bot.db
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"